### ISSUE TITLE
Circuit diagram for motor encoder

### ISSUE THREAD

**Issue by RepRapThailand** [agnunez/stm32duino_2DCMotor_Encoders#1]
Hi,

I am a newbie for STM32. I much inrerested in "STM32duino 2DC Motor Encoders" and need circuit diagram for interface STM32, encoder and L298N module. What are pin number for red question mark?

![schematic2](https://user-images.githubusercontent.com/15525407/41138467-0e03364c-6ad1-11e8-8e88-820b8eb8c091.png)

Best Regards,

KK.

**Comment by agnunez** [comment]
The pinout is configured in the code for two DC motors, not stepper, so STEP DIR in your diagram are not supported yet.

  pinMode(PB0, INPUT);  // Enc A Motor 1  for reading interrupts
  pinMode(PB1, INPUT);  // Enc B Motor 1  
  pinMode(PA0, PWM);  H-Bridge in1 Motor 1
  pinMode(PA1, PWM);  H Bridge In2 Motor 1

Similarly, there are other pins for motor 2, as on STM32 can drive two of them in this code.

PB0... PA1 etc are printed in circuit pin.

Regards,
